name: Build deploy release
on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency:
    group: 'pages-${{ github.ref }}'
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6.0.2

            # BUILD
            - name: Use node
              uses: actions/setup-node@v6.3.0
              with:
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Check formatting
              run: npm run format:check

            - name: Lint
              run: npm run lint

            - name: Type check
              run: npm run typecheck

            - name: Build
              run: npm run build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v5.0.0
              with:
                  path: './public'

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            # DEPLOY
            - name: Setup Pages
              uses: actions/configure-pages@v6.0.0

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v3.0.0

    release:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v6.0.2

            # BUILD
            - name: Use node
              uses: actions/setup-node@v6.3.0
              with:
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            # RELEASE
            - name: Compress public directory
              run: zip -r InstaSweep.zip public/

            - name: Get current date and time
              id: datetime
              run: echo "datetime=$(date '+%Y.%m.%d_%H%M')" >> "$GITHUB_OUTPUT"

            - name: Create Release
              uses: softprops/action-gh-release@v3.0.0
              with:
                  files: InstaSweep.zip
                  tag_name: ${{ steps.datetime.outputs.datetime }}_${{ github.sha }}
                  body: Release notes
                  draft: false
                  prerelease: false
