name: Build deploy release
on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency:
    group: 'pages'
    cancel-in-progress: false

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    update_and_deploy:
        runs-on: ubuntu-latest

        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - uses: actions/checkout@v3

            # BUILD
            - name: Use node
              uses: actions/setup-node@v3
              with:
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            # DEPLOY
            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: './public'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2

            # RELEASE
            - name: Compress folder
              run: zip -r InstaSweep.zip public/

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: InstaSweep.zip
